name: Update Profile

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update README
      run: |
        curl -o wallpaper.jpg https://bing.img.run/uhd.php
        
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

        git commit -am "Update Wallpaper"
        git push
