name: Update Profile

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update README
      run: |
        date=$(date +%Y%m%d%H%M%S)
        
        mkdir -p images
        
        rm -f images/bing_*.jpg

        wget --no-check-certificate -O images/bing_$date.jpg https://bing.img.run/uhd.php

        sed -i "s|images/.*.jpg|images/bing_$date.jpg|g" README.md
        
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        git add images
        git commit -am "Update Wallpaper"
        git push
