name: Update Profile

on:
  schedule:
    - cron: '17 7 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update README
      run: |
        date=$(date +%Y%m%d%H%M%S)
        sed -i "s|https://bing.img.run/uhd.php?time=[^\"]*|https://bing.img.run/uhd.php?time=$date|g" README.md
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Update README.md"
        git push